[target.x86_64-unknown-linux-gnu]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "export TZ=Etc/UTC",
    "dpkg --add-architecture amd64",
    "apt update -q && apt upgrade -yq && apt install --assume-yes --no-install-recommends libclang-10-dev clang-10 cmake build-essential pkg-config libssl-dev:amd64 libssl-dev:amd64-static libsasl2-dev gnutls-bin file strace",
    "apt install -y gcc-10 g++-10",
    "update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10",
    "update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "dpkg --add-architecture arm64",
    "apt-get update -q && apt-get install --assume-yes --no-install-recommends libssl-dev:arm64 libssl-dev:arm64-static pkg-config perl binutils-aarch64-linux-gnu file strace",
    "apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu"
]