[target.x86_64-unknown-linux-gnu]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "export TZ=Etc/UTC",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -q && apt upgrade -yq",
    "apt install --assume-yes --no-install-recommends libssl-dev:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH-static clang cmake build-essential pkg-config libsasl2-dev gnutls-bin",
    "apt install -y gcc-10 g++-10",
    "update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10",
    "update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update -q && apt-get install --assume-yes --no-install-recommends libssl-dev:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH-static pkg-config",
]
